[build]
apt_packages = ["libgl1-mesa-glx", "libglib2.0-0", "libsm6", "libxext6", "libxrender1"]

[deploy]
startCommand = "hypercorn app.main:app --bind \"[::]:$PORT\""
restartPolicyType = "ON_FAILURE"
